# Generated by Django 4.1.4 on 2022-12-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
